name: crypto_shadow
description: CryptoCurrency Tracker for Android &amp; iOS
author: Hugo EXTRAT <www.hugoextrat.com>
homepage: https://github.com/huextrat/CryptoShadow

dependencies:
  flutter:
    sdk: flutter
  intl: 0.15.2
  sqflite: 0.8.4
  path_provider: "^0.4.0"
  timeago: "^1.2.0"
  flutter_webview_plugin: "^0.1.4"
  flutter_circular_chart: "^0.0.2"
  cupertino_icons: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/loading.gif
    - assets/CryptoShadow_logo.png
    - assets/img/act.png
    - assets/img/ada.png
    - assets/img/adx.png
    - assets/img/ae.png
    - assets/img/agi.png
    - assets/img/aion.png
    - assets/img/amb.png
    - assets/img/amp.png
    - assets/img/ant.png
    - assets/img/appc.png
    - assets/img/ardr.png
    - assets/img/ark.png
    - assets/img/arn.png
    - assets/img/ast.png
    - assets/img/atm.png
    - assets/img/bat.png
    - assets/img/bay.png
    - assets/img/bcc.png
    - assets/img/bcd.png
    - assets/img/bch.png
    - assets/img/bcn.png
    - assets/img/bco.png
    - assets/img/bcpt.png
    - assets/img/bdl.png
    - assets/img/bela.png
    - assets/img/blcn.png
    - assets/img/blk.png
    - assets/img/block.png
    - assets/img/bnb.png
    - assets/img/bnt.png
    - assets/img/bnty.png
    - assets/img/bpt.png
    - assets/img/bq.png
    - assets/img/bqx.png
    - assets/img/btc.png
    - assets/img/btcd.png
    - assets/img/btcz.png
    - assets/img/btg.png
    - assets/img/btm.png
    - assets/img/bts.png
    - assets/img/btx.png
    - assets/img/burst.png
    - assets/img/cdn.png
    - assets/img/cdt.png
    - assets/img/clam.png
    - assets/img/cloak.png
    - assets/img/cnd.png
    - assets/img/cnx.png
    - assets/img/cny.png
    - assets/img/cred.png
    - assets/img/crpt.png
    - assets/img/cvc.png
    - assets/img/dash.png
    - assets/img/dat.png
    - assets/img/data.png
    - assets/img/dbc.png
    - assets/img/dcn.png
    - assets/img/dcr.png
    - assets/img/dent.png
    - assets/img/dgb.png
    - assets/img/dgd.png
    - assets/img/dlt.png
    - assets/img/dnt.png
    - assets/img/doge.png
    - assets/img/drgn.png
    - assets/img/ebst.png
    - assets/img/edg.png
    - assets/img/edoge.png
    - assets/img/elf.png
    - assets/img/elix.png
    - assets/img/ella.png
    - assets/img/emc.png
    - assets/img/emc2.png
    - assets/img/eng.png
    - assets/img/enj.png
    - assets/img/eos.png
    - assets/img/etc.png
    - assets/img/eth.png
    - assets/img/ethos.png
    - assets/img/etn.png
    - assets/img/etp.png
    - assets/img/eur.png
    - assets/img/evx.png
    - assets/img/exmo.png
    - assets/img/exp.png
    - assets/img/fair.png
    - assets/img/fct.png
    - assets/img/fil.png
    - assets/img/fldc.png
    - assets/img/flo.png
    - assets/img/ftc.png
    - assets/img/fuel.png
    - assets/img/fun.png
    - assets/img/game.png
    - assets/img/gas.png
    - assets/img/gbp.png
    - assets/img/gbx.png
    - assets/img/gbyte.png
    - assets/img/gno.png
    - assets/img/gnt.png
    - assets/img/grc.png
    - assets/img/grs.png
    - assets/img/gto.png
    - assets/img/gup.png
    - assets/img/gvt.png
    - assets/img/gxs.png
    - assets/img/hpb.png
    - assets/img/hsr.png
    - assets/img/huc.png
    - assets/img/hush.png
    - assets/img/icn.png
    - assets/img/icx.png
    - assets/img/ignis.png
    - assets/img/ins.png
    - assets/img/iop.png
    - assets/img/iost.png
    - assets/img/jpy.png
    - assets/img/kcs.png
    - assets/img/kin.png
    - assets/img/kmd.png
    - assets/img/knc.png
    - assets/img/krb.png
    - assets/img/lbc.png
    - assets/img/lend.png
    - assets/img/link.png
    - assets/img/lkk.png
    - assets/img/lrc.png
    - assets/img/lsk.png
    - assets/img/ltc.png
    - assets/img/lun.png
    - assets/img/maid.png
    - assets/img/mana.png
    - assets/img/mcap.png
    - assets/img/mco.png
    - assets/img/med.png
    - assets/img/miota.png
    - assets/img/mkr.png
    - assets/img/mln.png
    - assets/img/mnx.png
    - assets/img/mona.png
    - assets/img/mth.png
    - assets/img/mtl.png
    - assets/img/music.png
    - assets/img/nano.png
    - assets/img/nas.png
    - assets/img/nav.png
    - assets/img/ndz.png
    - assets/img/nebl.png
    - assets/img/neo.png
    - assets/img/neos.png
    - assets/img/ngc.png
    - assets/img/nlc2.png
    - assets/img/nlg.png
    - assets/img/nmc.png
    - assets/img/nxs.png
    - assets/img/nxt.png
    - assets/img/oax.png
    - assets/img/omg.png
    - assets/img/omni.png
    - assets/img/ost.png
    - assets/img/ox.png
    - assets/img/pac.png
    - assets/img/part.png
    - assets/img/pasl.png
    - assets/img/pay.png
    - assets/img/pink.png
    - assets/img/pirl.png
    - assets/img/pivx.png
    - assets/img/plr.png
    - assets/img/poe.png
    - assets/img/poly.png
    - assets/img/pot.png
    - assets/img/powr.png
    - assets/img/ppc.png
    - assets/img/ppp.png
    - assets/img/ppt.png
    - assets/img/prl.png
    - assets/img/pura.png
    - assets/img/qash.png
    - assets/img/qiwi.png
    - assets/img/qlc.png
    - assets/img/qsp.png
    - assets/img/qtum.png
    - assets/img/r.png
    - assets/img/rads.png
    - assets/img/rcn.png
    - assets/img/rdd.png
    - assets/img/rdn.png
    - assets/img/rep.png
    - assets/img/req.png
    - assets/img/rhoc.png
    - assets/img/ric.png
    - assets/img/rise.png
    - assets/img/rlc.png
    - assets/img/rpx.png
    - assets/img/rub.png
    - assets/img/salt.png
    - assets/img/san.png
    - assets/img/sbd.png
    - assets/img/sberbank.png
    - assets/img/sc.png
    - assets/img/sky.png
    - assets/img/smart.png
    - assets/img/sngls.png
    - assets/img/snt.png
    - assets/img/sonm.png
    - assets/img/sphtx.png
    - assets/img/srn.png
    - assets/img/start.png
    - assets/img/steem.png
    - assets/img/storj.png
    - assets/img/storm.png
    - assets/img/strat.png
    - assets/img/sub.png
    - assets/img/sys.png
    - assets/img/taas.png
    - assets/img/tau.png
    - assets/img/tix.png
    - assets/img/tkn.png
    - assets/img/tnc.png
    - assets/img/tnt.png
    - assets/img/trig.png
    - assets/img/trx.png
    - assets/img/tzc.png
    - assets/img/ubq.png
    - assets/img/usd.png
    - assets/img/usdt.png
    - assets/img/ven.png
    - assets/img/veri.png
    - assets/img/via.png
    - assets/img/vibe.png
    - assets/img/vivo.png
    - assets/img/vrc.png
    - assets/img/vtc.png
    - assets/img/wabi.png
    - assets/img/waves.png
    - assets/img/wax.png
    - assets/img/wtc.png
    - assets/img/xbc.png
    - assets/img/xcp.png
    - assets/img/xdn.png
    - assets/img/xem.png
    - assets/img/xlm.png
    - assets/img/xmg.png
    - assets/img/xmr.png
    - assets/img/xmy.png
    - assets/img/xp.png
    - assets/img/xpa.png
    - assets/img/xpm.png
    - assets/img/xrp.png
    - assets/img/xtz.png
    - assets/img/xuc.png
    - assets/img/xvc.png
    - assets/img/xvg.png
    - assets/img/xzc.png
    - assets/img/yoyow.png
    - assets/img/zcl.png
    - assets/img/zec.png
    - assets/img/zen.png
    - assets/img/zil.png
    - assets/img/zrx.png


  fonts:
      - family: Poppins
        fonts:
          - asset: assets/fonts/Poppins-Regular.ttf
            weight: 500
          - asset: assets/fonts/Poppins-SemiBold.ttf
            weight: 600